use std::collections::HashSet;
use std::net::SocketAddr;
use std::sync::Arc;

use rand::RngCore;
use rand::rngs::OsRng;

use crate::pool::SocksAuth;
use crate::tor::error::TorIdentityError;

/// One runtime-only SOCKS identity generated by [`TorIdentityPool`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TorIdentity {
    id: u64,
    proxy_addr: SocketAddr,
    auth: SocksAuth,
}

impl TorIdentity {
    /// This identity's index within its [`TorIdentityPool`].
    pub fn id(&self) -> u64 {
        self.id
    }

    /// The shared Tor SOCKS5 listener address for this identity.
    pub fn proxy_addr(&self) -> SocketAddr {
        self.proxy_addr
    }

    /// This identity's SOCKS5 username. Safe to log.
    pub fn username(&self) -> &str {
        self.auth.username()
    }

    /// This identity's SOCKS5 password. The caller must not log this value.
    pub fn expose_password(&self) -> &str {
        self.auth.expose_password()
    }
}

/// Runtime-only SOCKS identities for Tor stream isolation.
///
/// Different SOCKS username/password pairs cause Tor to isolate streams and
/// circuits when `IsolateSOCKSAuth` is enabled. This does not guarantee a
/// unique exit relay IP for each identity.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TorIdentityPool {
    identities: Vec<TorIdentity>,
}

impl TorIdentityPool {
    /// Generates `count` identities sharing `proxy_addr`, each with a
    /// unique username and password.
    pub fn generate(proxy_addr: SocketAddr, count: usize) -> Result<Self, TorIdentityError> {
        if count == 0 {
            return Err(TorIdentityError::EmptyIdentityPool);
        }

        let mut identities = Vec::with_capacity(count);
        let mut passwords = HashSet::with_capacity(count);

        for id in 0..count {
            let username = format!("worker-{id:06}");
            let mut password = random_hex(32)?;
            while !passwords.insert(password.clone()) {
                password = random_hex(32)?;
            }

            identities.push(TorIdentity {
                id: id as u64,
                proxy_addr,
                auth: SocksAuth {
                    username: Arc::from(username),
                    password: Arc::from(password),
                },
            });
        }

        Ok(Self { identities })
    }

    /// The number of identities in this pool.
    pub fn identity_count(&self) -> usize {
        self.identities.len()
    }

    /// The identity at `index`, if any.
    pub fn isolated_identity(&self, index: usize) -> Option<&TorIdentity> {
        self.identities.get(index)
    }

    /// Deprecated alias for [`TorIdentityPool::isolated_identity`].
    #[deprecated(
        since = "0.2.0",
        note = "use `TorIdentityPool::isolated_identity` instead"
    )]
    pub fn get(&self, index: usize) -> Option<&TorIdentity> {
        self.isolated_identity(index)
    }

    /// All identities in this pool.
    pub fn identities(&self) -> &[TorIdentity] {
        &self.identities
    }
}

fn random_hex(bytes: usize) -> Result<String, TorIdentityError> {
    let mut random = vec![0_u8; bytes];
    secure_random(&mut random)?;
    Ok(hex_encode(&random))
}

fn secure_random(bytes: &mut [u8]) -> Result<(), TorIdentityError> {
    OsRng.try_fill_bytes(bytes)?;
    Ok(())
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push(HEX[(byte >> 4) as usize] as char);
        out.push(HEX[(byte & 0x0f) as usize] as char);
    }
    out
}
